name: scan for secrets
on:
  schedule:
  - cron: "0 9 * * *"

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: trufflehog-actions-scan
      uses: edplato/trufflehog-actions-scan@master
      with:
        scanArguments: "--regex --entropy=False --max_depth=1"
        githubToken: ${{ secrets.ACCESS_TOKEN }}
    - name: Slack Notification
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2.0.2
      env:
        SLACK_CHANNEL: github-token-scan
        SLACK_COLOR: '#3278BD'
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: '@devops-team Secrets were found in repo, please check out the above actions link for more details'
        SLACK_USERNAME: github-token-scan
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
